export const FETCH_ROOTS = '@@internal/FETCH_ROOTS';
export const FETCH_ROOTS_FAILURE = '@@internal/FETCH_ROOTS_FAILURE';
export const FETCH_ROOTS_SUCCESS = '@@internal/FETCH_ROOTS_SUCCESS';
export const FETCH_RESOURCES = '@@internal/FETCH_RESOURCES';
export const FETCH_RESOURCES_FAILURE = '@@internal/FETCH_RESOURCES_FAILURE';
export const FETCH_RESOURCES_SUCCESS = '@@internal/FETCH_RESOURCES_SUCCESS';
export const SET_FAVOURITE_CATEGORY = '@@internal/SET_FAVOURITE_CATEGORY';
export const REMOVE_FAVOURITE_CATEGORY = '@@internal/REMOVE_FAVOURITE_CATEGORY';
